# For a complete list of hooks, see:
# https://github.com/sds/overcommit/tree/master/lib/overcommit/hook
#
# For a complete list of options that you can use to customize hooks, see:
# https://github.com/sds/overcommit#configuration
#
PreCommit:
  EsLint:
    enabled: true
    on_warn: fail
    quiet: false
    required_executable: 'npm'
    command: ['npm', 'run', 'lint-full', '--', '-f', 'compact']
    include:
      - '**/*.js'
      - '**/*.ts'
    exclude:
     - 'src/public/**/*'
  NpmTest:
    enabled: true
    quiet: false
    description: 'Check tests and coverage'
    command: ['npx', 'jest', '--coverage']
    include:
      - '**/*.ts'
  TrailingWhitespace:
    enabled: true
    exclude:
     - 'dist/**/*'
  LineEndings:
    enabled: true
    include:
      - '**/*.{js,ts,json}'

# CommitMsg:
#   SpellCheck:
#     enabled: true
#     # on_warn: fail

# PostCheckout:
#   ALL: # Special hook name that customizes all hooks of this type
#     quiet: true # Change all post-checkout hooks to only display output on failure
#   IndexTags:
#     enabled: true # Generate a tags file with `ctags` each time HEAD changes
